/* tslint:disable */
/* eslint-disable */
/**
 * Dynamic API Specification
 * This is a dynamically generated API specification for all endpoints existing on the current project.
 *
 * The version of the OpenAPI document: 10.13.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CreateFolderRequest
 */
export interface CreateFolderRequest {
  /**
   * Name of the folder.
   * @type {string}
   * @memberof CreateFolderRequest
   */
  name: string;
  /**
   * Unique identifier of the parent folder. This allows for nested folders.
   * @type {number}
   * @memberof CreateFolderRequest
   */
  parent?: number;
}
