/* tslint:disable */
/* eslint-disable */
/**
 * Dynamic API Specification
 * This is a dynamically generated API specification for all endpoints existing on the current project.
 *
 * The version of the OpenAPI document: 10.13.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The meta info.
 * @export
 * @interface CreateFieldRequestMeta
 */
export interface CreateFieldRequestMeta {
  /**
   * Unique identifier for the field in the `directus_fields` collection.
   * @type {number}
   * @memberof CreateFieldRequestMeta
   */
  id?: number;
  /**
   * Unique name of the collection this field is in.
   * @type {string}
   * @memberof CreateFieldRequestMeta
   */
  collection?: string;
  /**
   * Unique name of the field. Field name is unique within the collection.
   * @type {string}
   * @memberof CreateFieldRequestMeta
   */
  field?: string;
  /**
   * Transformation flag for field
   * @type {Array<string>}
   * @memberof CreateFieldRequestMeta
   */
  special?: Array<string> | null;
  /**
   * What interface is used in the admin app to edit the value for this field.
   * @type {string}
   * @memberof CreateFieldRequestMeta
   */
  "system-interface"?: string | null;
  /**
   * Options for the interface that\'s used. This format is based on the individual interface.
   * @type {object}
   * @memberof CreateFieldRequestMeta
   */
  options?: object | null;
  /**
   * What display is used in the admin app to display the value for this field.
   * @type {string}
   * @memberof CreateFieldRequestMeta
   */
  display?: string | null;
  /**
   * Options for the display that\'s used. This format is based on the individual display.
   * @type {object}
   * @memberof CreateFieldRequestMeta
   */
  display_options?: object | null;
  /**
   * If the field can be altered by the end user. Directus system fields have this value set to `true`.
   * @type {boolean}
   * @memberof CreateFieldRequestMeta
   */
  locked?: boolean;
  /**
   * Prevents the user from editing the value in the field.
   * @type {boolean}
   * @memberof CreateFieldRequestMeta
   */
  readonly?: boolean;
  /**
   * If this field should be hidden.
   * @type {boolean}
   * @memberof CreateFieldRequestMeta
   */
  hidden?: boolean;
  /**
   * Sort order of this field on the edit page of the admin app.
   * @type {number}
   * @memberof CreateFieldRequestMeta
   */
  sort?: number | null;
  /**
   * Width of the field on the edit form.
   * @type {string}
   * @memberof CreateFieldRequestMeta
   */
  width?: CreateFieldRequestMetaWidthEnum | null;
  /**
   * What field group this field is part of.
   * @type {number}
   * @memberof CreateFieldRequestMeta
   */
  group?: number | null;
  /**
   * Key value pair of `<language>: <translation>` that allows the user to change the displayed name of the field in the admin app.
   * @type {object}
   * @memberof CreateFieldRequestMeta
   */
  translation?: object | null;
  /**
   * A user provided note for the field. Will be rendered alongside the interface on the edit page.
   * @type {string}
   * @memberof CreateFieldRequestMeta
   */
  note?: string | null;
}

export const CreateFieldRequestMetaWidthEnum = {
  Half: "half",
  HalfLeft: "half-left",
  HalfRight: "half-right",
  Full: "full",
  Fill: "fill",
  Null: "null",
} as const;

export type CreateFieldRequestMetaWidthEnum =
  (typeof CreateFieldRequestMetaWidthEnum)[keyof typeof CreateFieldRequestMetaWidthEnum];
