/* tslint:disable */
/* eslint-disable */
/**
 * Dynamic API Specification
 * This is a dynamically generated API specification for all endpoints existing on the current project.
 *
 * The version of the OpenAPI document: 10.13.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetAsset404ResponseError
 */
export interface GetAsset404ResponseError {
  /**
   *
   * @type {number}
   * @memberof GetAsset404ResponseError
   */
  code?: number;
  /**
   *
   * @type {string}
   * @memberof GetAsset404ResponseError
   */
  message?: string;
}
