/* tslint:disable */
/* eslint-disable */
/**
 * Dynamic API Specification
 * This is a dynamically generated API specification for all endpoints existing on the current project.
 *
 * The version of the OpenAPI document: 10.13.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Oauth200Response
 */
export interface Oauth200Response {
    /**
     * 
     * @type {boolean}
     * @memberof Oauth200Response
     */
    'public'?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof Oauth200Response
     */
    'data'?: Array<string>;
}

