/* tslint:disable */
/* eslint-disable */
/**
 * Dynamic API Specification
 * This is a dynamically generated API specification for all endpoints existing on the current project.
 *
 * The version of the OpenAPI document: 10.13.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PasswordResetRequest
 */
export interface PasswordResetRequest {
    /**
     * One-time use JWT token that is used to verify the user.
     * @type {string}
     * @memberof PasswordResetRequest
     */
    'token': string;
    /**
     * New password for the user.
     * @type {string}
     * @memberof PasswordResetRequest
     */
    'password': string;
}

