/* tslint:disable */
/* eslint-disable */
/**
 * Dynamic API Specification
 * This is a dynamically generated API specification for all endpoints existing on the current project.
 *
 * The version of the OpenAPI document: 10.13.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Refresh200ResponseData
 */
export interface Refresh200ResponseData {
  /**
   *
   * @type {string}
   * @memberof Refresh200ResponseData
   */
  access_token?: string;
  /**
   *
   * @type {number}
   * @memberof Refresh200ResponseData
   */
  expires?: number;
  /**
   *
   * @type {string}
   * @memberof Refresh200ResponseData
   */
  refresh_token?: string;
}
