/* tslint:disable */
/* eslint-disable */
/**
 * ASPA Portal V3 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateUserByIdRequest
 */
export interface UpdateUserByIdRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateUserByIdRequest
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserByIdRequest
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserByIdRequest
     */
    'lastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserByIdRequest
     */
    'university'?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateUserByIdRequest
     */
    'studentId'?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserByIdRequest
     */
    'upi'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserByIdRequest
     */
    'skillLevel'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserByIdRequest
     */
    'phoneNumber'?: string;
}

