/* tslint:disable */
/* eslint-disable */
/**
 * ASPA Portal V3 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * Unique identifier for the User.
     * @type {number}
     * @memberof User
     */
    'id': number;
    /**
     * Email address of the User.
     * @type {string}
     * @memberof User
     */
    'email': string;
    /**
     * First name of the User.
     * @type {string}
     * @memberof User
     */
    'firstName': string;
    /**
     * Last name of the User.
     * @type {string}
     * @memberof User
     */
    'lastName': string;
    /**
     * University the User attends, if applicable.
     * @type {string}
     * @memberof User
     */
    'university'?: string;
    /**
     * Unique student identifier, if applicable.
     * @type {number}
     * @memberof User
     */
    'studentId'?: number;
    /**
     * Unique personal identifier, if applicable.
     * @type {string}
     * @memberof User
     */
    'upi'?: string;
    /**
     * Role of the User in the system.
     * @type {string}
     * @memberof User
     */
    'role': string;
    /**
     * Skill level of the User.
     * @type {string}
     * @memberof User
     */
    'skillLevel': string;
    /**
     * Contact phone number of the User.
     * @type {string}
     * @memberof User
     */
    'phoneNumber': string;
}

