import ProfileForm from "../../ui/profile-page/ProfileCard"
import UpcomingEvents from "../../ui/profile-page/UpcomingEvents"
import ParticipatedEvents from "../../ui/profile-page/ParticipatedEvents"
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "ASPA - Profile Page",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>
      <ProfileForm />
      <UpcomingEvents />
      <ParticipatedEvents />
    </div>
  );
}