swagger: '2.0'
basePath: '/'
info:
  title: 'ASPA Portal V3 API'
  version: '1.0.0'
definitions:
  User:
    type: 'object'
    properties:
      id:
        type: 'integer'
        format: 'int32'
        description: Unique identifier for the User.
      email:
        type: 'string'
        format: email
        description: Email address of the User.
      firstName:
        type: 'string'
        description: First name of the User.
      lastName:
        type: 'string'
        description: Last name of the User.
      university:
        type: 'string'
        description: University the User attends, if applicable.
      studentId:
        type: 'integer'
        format: 'int32'
        description: Unique student identifier, if applicable.
      upi:
        type: 'string'
        description: Unique personal identifier, if applicable.
      role:
        type: 'string'
        default: user
        description: Role of the User in the system.
      skillLevel:
        type: 'string'
        description: Skill level of the User.
      phoneNumber:
        type: 'string'
        description: Contact phone number of the User.
    required:
      - 'id'
      - 'email'
      - 'firstName'
      - 'lastName'
      - 'role'
      - 'skillLevel'
      - 'phoneNumber'
  Event:
    type: 'object'
    properties:
      id:
        type: 'integer'
        format: 'int32'
      name:
        type: 'string'
      dateTime:
        type: 'string'
        format: 'date-time'
      venue:
        type: 'string'
      description:
        type: 'string'
      price:
        type: 'number'
        format: 'double'
      createdBy:
        type: 'string'
      attendingExec:
        type: 'string'
      imageUrl:
        type: 'string'
    required:
      - 'id'
      - 'name'
      - 'dateTime'
      - 'venue'
      - 'price'
      - 'createdBy'
  Ticket:
    type: 'object'
    properties:
      id:
        type: 'integer'
        format: 'int32'
      userId:
        type: 'integer'
        format: 'int32'
      eventId:
        type: 'integer'
        format: 'int32'
      isPaid:
        type: 'boolean'
      paymentDateTime:
        type: 'string'
        format: 'date-time'
      paymentMethod:
        type: 'string'
      paymentAmount:
        type: 'number'
        format: 'double'
    required:
      - 'id'
      - 'userId'
      - 'eventId'
      - 'isPaid'
      - 'paymentDateTime'
      - 'paymentMethod'
      - 'paymentAmount'
  Exec:
    type: 'object'
    properties:
      id:
        type: 'integer'
        format: 'int32'
      name:
        type: 'string'
      title:
        type: 'string'
      description:
        type: 'string'
      imageUrl:
        type: 'string'
    required:
      - 'id'
      - 'name'
      - 'title'
      - 'description'
paths: {}
