swagger: '2.0'
basePath: '/'
info:
  title: 'A getting started API.'
  version: '1.0.0'
definitions:
  User:
    type: 'object'
    properties:
      id:
        type: 'integer'
        format: 'int64'
      email:
        type: 'string'
      firstName:
        type: 'string'
      lastName:
        type: 'string'
      university:
        type: 'string'
      studentId:
        type: 'string'
      upi:
        type: 'string'
      role:
        type: 'string'
      skillLevel:
        type: 'string'
      phoneNumber:
        type: 'string'
    required:
      - 'id'
      - 'email'
      - 'firstName'
      - 'lastName'
      - 'role'
      - 'skillLevel'
      - 'phoneNumber'
  Event:
    type: 'object'
    properties:
      id:
        type: 'integer'
        format: 'int64'
      name:
        type: 'string'
      dateTime:
        type: 'string'
        format: 'date-time'
      venue:
        type: 'string'
      description:
        type: 'string'
      price:
        type: 'number'
        format: 'double'
      createdBy:
        type: 'string'
      attendingExec:
        type: 'string'
      imageUrl:
        type: 'string'
    required:
      - 'id'
      - 'name'
      - 'dateTime'
      - 'venue'
      - 'price'
      - 'createdBy'
  Ticket:
    type: 'object'
    properties:
      id:
        type: 'integer'
        format: 'int64'
      userId:
        type: 'integer'
        format: 'int64'
      eventId:
        type: 'integer'
        format: 'int64'
      isPaid:
        type: 'boolean'
      paymentDateTime:
        type: 'string'
        format: 'date-time'
      paymentMethod:
        type: 'string'
      paymentAmount:
        type: 'number'
        format: 'double'
    required:
      - 'id'
      - 'userId'
      - 'eventId'
      - 'isPaid'
      - 'paymentDateTime'
      - 'paymentMethod'
      - 'paymentAmount'
  Exec:
    type: 'object'
    properties:
      id:
        type: 'integer'
        format: 'int64'
      name:
        type: 'string'
      title:
        type: 'string'
      description:
        type: 'string'
      imageUrl:
        type: 'string'
    required:
      - 'id'
      - 'name'
      - 'title'
      - 'description'
paths: {}
