import type { Metadata } from "next";
import Footer from "@/ui/Footer";
import Header from "@/ui/Header";
import { zillaSlab } from "@/ui/fonts";
import "./globals.css";
import Login from "./home/login/page";
import SignIn from "./components/sign-in";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${zillaSlab.className} antialiased`}>
        <Header/>
        <main>
          {children}
          {/* <SignIn /> */}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
