# fly.toml app configuration file generated for repo-rough-fog-7201 on 2025-08-18T03:42:19Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aspa-portal-v3'
primary_region = 'syd'
swap_size_mb = 512

[build]

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

[[services.ports]]
  handlers = ["http"]
  internal_port = 3000
  port = 80
  force_https = true


[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
