version: '3.1'

services:
  db:
    container_name: aspa-db
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aspadb
      MYSQL_USER: aspa
      MYSQL_PASSWORD: pool
      MYSQL_TCP_PORT: 3307
    ports:
      - 3307:3307
    expose:
      - 3307

  adminer:
    container_name: aspa-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080