services:
  db:
    image: postgres
    restart: on-failure
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: aspa
      POSTGRES_USER: payload
    networks:
      - aspa-network

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - aspa-network

  x11-bridge:
    image: jare/x11-bridge
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    ports:
      - "10000:10000"
    restart: always
    environment:
      MODE: tcp
      XPRA_HTML: "yes"
      DISPLAY: :14
      XPRA_PASSWORD: MUST_BE_SOMETHING

networks:
  aspa-network:
    driver: bridge
