name: aspa-dev-container
services:
  app:
    container_name: aspa-app
    build:
      context: ../../../../
      dockerfile: ./dockerfile/Dockerfile
    network_mode: "host"
    volumes:
      - .:/repo
    environment:
      - NODE_ENV=development
    command: sh -c "while sleep 1000; do :; done"