services:
  db:
    image: postgres
    restart: on-failure
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: aspa
      POSTGRES_USER: payload
    networks:
      - aspa-network

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - aspa-network