/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Humanitix Public API
 * The Humanitix Public API for fetching event, order, ticket or tag information. Please note that in periods of low activity the first request you make may take a few seconds longer than normal.
 * OpenAPI spec version: 1.18.0
 */
import type {
  GetV1EventsEventIdOrders200,
  GetV1EventsEventIdOrdersOrderIdParams,
  GetV1EventsEventIdOrdersParams,
  InternalServerError,
  NotFoundError,
  Order,
  UnauthorizedError
} from '../humanitixPublicAPI.schemas';



export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;

/**
 * Returns all orders for a given event and eventDateId.
 * @summary Get Orders
 */
export type getV1EventsEventIdOrdersResponse200 = {
  data: GetV1EventsEventIdOrders200
  status: 200
}

export type getV1EventsEventIdOrdersResponse401 = {
  data: UnauthorizedError
  status: 401
}

export type getV1EventsEventIdOrdersResponse404 = {
  data: NotFoundError
  status: 404
}

export type getV1EventsEventIdOrdersResponseDefault = {
  data: InternalServerError
  status: Exclude<HTTPStatusCodes, 200 | 401 | 404>
}
    
export type getV1EventsEventIdOrdersResponseComposite = getV1EventsEventIdOrdersResponse200 | getV1EventsEventIdOrdersResponse401 | getV1EventsEventIdOrdersResponse404 | getV1EventsEventIdOrdersResponseDefault;
    
export type getV1EventsEventIdOrdersResponse = getV1EventsEventIdOrdersResponseComposite & {
  headers: Headers;
}

export const getGetV1EventsEventIdOrdersUrl = (eventId: string,
    params: GetV1EventsEventIdOrdersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/events/${eventId}/orders?${stringifiedParams}` : `/v1/events/${eventId}/orders`
}

export const getV1EventsEventIdOrders = async (eventId: string,
    params: GetV1EventsEventIdOrdersParams, options?: RequestInit): Promise<getV1EventsEventIdOrdersResponse> => {
  
  const res = await fetch(getGetV1EventsEventIdOrdersUrl(eventId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getV1EventsEventIdOrdersResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getV1EventsEventIdOrdersResponse
}


/**
 * Returns an order for the given eventId.
 * @summary Get Order
 */
export type getV1EventsEventIdOrdersOrderIdResponse200 = {
  data: Order
  status: 200
}

export type getV1EventsEventIdOrdersOrderIdResponse401 = {
  data: UnauthorizedError
  status: 401
}

export type getV1EventsEventIdOrdersOrderIdResponse404 = {
  data: NotFoundError
  status: 404
}

export type getV1EventsEventIdOrdersOrderIdResponseDefault = {
  data: InternalServerError
  status: Exclude<HTTPStatusCodes, 200 | 401 | 404>
}
    
export type getV1EventsEventIdOrdersOrderIdResponseComposite = getV1EventsEventIdOrdersOrderIdResponse200 | getV1EventsEventIdOrdersOrderIdResponse401 | getV1EventsEventIdOrdersOrderIdResponse404 | getV1EventsEventIdOrdersOrderIdResponseDefault;
    
export type getV1EventsEventIdOrdersOrderIdResponse = getV1EventsEventIdOrdersOrderIdResponseComposite & {
  headers: Headers;
}

export const getGetV1EventsEventIdOrdersOrderIdUrl = (eventId: string,
    orderId: string,
    params?: GetV1EventsEventIdOrdersOrderIdParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/events/${eventId}/orders/${orderId}?${stringifiedParams}` : `/v1/events/${eventId}/orders/${orderId}`
}

export const getV1EventsEventIdOrdersOrderId = async (eventId: string,
    orderId: string,
    params?: GetV1EventsEventIdOrdersOrderIdParams, options?: RequestInit): Promise<getV1EventsEventIdOrdersOrderIdResponse> => {
  
  const res = await fetch(getGetV1EventsEventIdOrdersOrderIdUrl(eventId,orderId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getV1EventsEventIdOrdersOrderIdResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getV1EventsEventIdOrdersOrderIdResponse
}


