/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Humanitix Public API
 * The Humanitix Public API for fetching event, order, ticket or tag information. Please note that in periods of low activity the first request you make may take a few seconds longer than normal.
 * OpenAPI spec version: 1.18.0
 */
import type {
  BadRequestError,
  ForbiddenError,
  GetV1GlobalEvents200,
  GetV1GlobalEventsParams,
  InternalServerError,
  UnauthorizedError
} from '../humanitixPublicAPI.schemas';



export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;

/**
 * Returns an array of events from across the platform. Requires special user permission to use this endpoint, activated by Humanitix.
 * @summary Get Events global
 */
export type getV1GlobalEventsResponse200 = {
  data: GetV1GlobalEvents200
  status: 200
}

export type getV1GlobalEventsResponse400 = {
  data: BadRequestError
  status: 400
}

export type getV1GlobalEventsResponse401 = {
  data: UnauthorizedError
  status: 401
}

export type getV1GlobalEventsResponse403 = {
  data: ForbiddenError
  status: 403
}

export type getV1GlobalEventsResponseDefault = {
  data: InternalServerError
  status: Exclude<HTTPStatusCodes, 200 | 400 | 401 | 403>
}
    
export type getV1GlobalEventsResponseComposite = getV1GlobalEventsResponse200 | getV1GlobalEventsResponse400 | getV1GlobalEventsResponse401 | getV1GlobalEventsResponse403 | getV1GlobalEventsResponseDefault;
    
export type getV1GlobalEventsResponse = getV1GlobalEventsResponseComposite & {
  headers: Headers;
}

export const getGetV1GlobalEventsUrl = (params: GetV1GlobalEventsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/global/events?${stringifiedParams}` : `/v1/global/events`
}

export const getV1GlobalEvents = async (params: GetV1GlobalEventsParams, options?: RequestInit): Promise<getV1GlobalEventsResponse> => {
  
  const res = await fetch(getGetV1GlobalEventsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()
  const data: getV1GlobalEventsResponse['data'] = body ? JSON.parse(body) : {}

  return { data, status: res.status, headers: res.headers } as getV1GlobalEventsResponse
}


