#!/bin/sh
# .husky/pre-commit

# Try to curl the URL and pipe the output to a file
curl http://0.0.0.0:8055/server/specs/oas -o ./backend/docs/api_docs.json



# Check if the curl command was successful
if [ $? -ne 0 ]; then
  echo "Curl command failed are you in the dev-container? Aborting commit."
  exit 1
fi

# Find and replace "url": "0.0.0.0:8055" with "url": "http://0.0.0.0:8055"
sed -i 's|"url": "0.0.0.0:8055"|"url": "http://0.0.0.0:8055"|g' ./backend/docs/api_docs.json

# Format the JSON file
jq . ./backend/docs/api_docs.json > ./backend/docs/api_docs.tmp && mv ./backend/docs/api_docs.tmp ./backend/docs/api_docs.json

# If successful, proceed with the commit
echo "Curl command succeeded. Proceeding with commit."