name: Tag, Build, and Push Docker Image for Main Branch

on:
  push:
    branches:
      - '**'  # run on any branch

jobs:
  versioning:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.versioning.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine branch name
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV

      - name: Determing Version
        id: versioning
        run: |
          git fetch --tags
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "0.0.0")
          IFS='.' read -r MAJOR MINOR PATCH <<< "$LATEST_TAG"

          BRANCH_NAME=${{ env.BRANCH_NAME }}

          if [[ "$BRANCH_NAME" == *feature* ]]; then
            MINOR=$((MINOR + 1))
            PATCH=0
          elif [[ "$BRANCH_NAME" == *bugfix* ]]; then
            PATCH=$((PATCH + 1))
          else
            echo "Branch name does not match feature/bugfix. Using patch increment."
            PATCH=$((PATCH + 1))
          fi

          NEW_TAG="$MAJOR.$MINOR.$PATCH"
          echo "tag=${NEW_TAG}" >> $GITHUB_OUTPUT
          echo "Computed tag: $NEW_TAG"

  build:
    needs: versioning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log branch and tag
        run: |
          echo "Branch: ${{ env.BRANCH_NAME }}"
          echo "Tag: ${{ needs.versioning.outputs.tag }}"

      - name: Build Docker image (dry run)
        run: |
          echo "Simulating Docker build..."
          echo "docker build -t test-image:${{ needs.versioning.outputs.tag }} ."
