name: Trigger re-deployment to render production

on:
  workflow_run:
    workflows: ["Tag, Build, Push Docker Image for Main Branch"] 
    types:
      - completed

jobs:
    deploy:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest
        steps:
            # Trigger re-deployment to render production
            - name: Deploy
              env:
                deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
              run: |
                curl "$deploy_url"
