name: Build API Client

on: [pull_request]

jobs:
    build:
        runs-on: ubuntu-latest   
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Run yarn install
              uses: borales/actions-yarn@v4
              with:
                cmd: install
            - name: Generate API Client
              run: yarn generate:api-client
    
        
