name: Frontend Tests

on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches: [ "main" ]
  #   types: [labeled, synchronize, opened, reopened]
  workflow_dispatch:

jobs:
  test_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare Yarn
        run: corepack prepare yarn@stable --activate

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/yarn
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run tests with yarn
        run: yarn jest --ci
