name: Frontend Tests

on:
    push

jobs:
  test_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare Yarn 4.9.1
        run: corepack prepare yarn@4.9.1 --activate

      - name: Install dependencies
        run: yarn install

      - name: Run tests with Jest
        run: npm run jest